import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Signup.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })



export default function Home() {

  const [ form, setForm ] = useState({
    firstname: "",
    lastname: "",
    email: "",
    password: ""
  })

  function handleFirstNameChange(e) {
    setForm({...form, firstname: e.target.value})
  }

  function handleLastNameChange(e) {
    setForm({...form, lastname: e.target.value})
  }

  function handleEmailChange(e) {
    setForm({...form, email: e.target.value})
  }

  function handlePasswordChange(e) {
    setForm({...form, password: e.target.value})
  }

  function validatePassword(password) {
    if (password.length > 8) {
      return true
    } else {
      return false
    }
  }


  return ( <>
      <Head>
        <title>Sign up form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

 <div className={styles.container}>
      <div className={styles.left}>
        <h1 className={styles.header}>Learn to code by watching others</h1>
        <p className={styles.description}>
          See how experienced developers solve problems in real-time. Watching scripted tutorials is great,
          but understanding how developers think is invaluable.
        </p>
      </div>

    <div className={styles.right}>
      <div className={styles.pricing}><span id={styles.boldstyle}>Try it free 7 days</span> then $20/mo. thereafter</div>
      <form action={console.log("submit")} className={styles.signupform}>

          <input className={styles.firstname} onChange={(e) => handleFirstNameChange(e)} placeholder="First Name" type="text" value={form.firstname} validation="fix this" required ></input>

          <input onChange={(e) => handleLastNameChange(e)} placeholder="Last Name" type="text" required />
          <input onChange={(e) => handleEmailChange(e)} placeholder="Email Address" type="email" required />
          <input onChange={(e) => handlePasswordChange(e)} placeholder="Password" type="password" minlength="8" required />
          <button className={styles.submit} type="submit" value="Submit">CLAIM YOUR FREE TRIAL</button>
          <p className={styles.terms}>By clicking the button, you are agreeing to our <span id={styles.redcolor}>Terms and Services</span></p>

      </form>
    </div>
  </div>
    </>
  )
}
